config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # get 'ask', to: 'pages#ask'
  get 'ask', to: 'questions#ask'
  get 'answer', to: 'questions#answer'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def ask
  end

  def answer
    if params[:ask] == "I am going to work"
      @answer = "Great!"
    elsif params[:ask].end_with?("?")
      @answer = "Silly question, get dressed and go to work!"
    else
      @answer = "I don't care, get dressed and go to work!"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/answer.html.erb
<div class="banner">
  <h1>Stupid coaching</h1>
</div>
  <p> 
    <%#= params %>
    <%= params[:ask] %><br/>You
    <%#= params[:controller] %>
    <%#= params[:action] %>
    
  </p>

  <p><%= @answer %><br/>Your Coach</p>

  <%= link_to "Ask a new question", ask_path %>

app/views/questions/ask.html.erb
<p>Ask your coach anything:</p>
<form action="answer">
  <input type="text" name="ask">
  <input type="submit" value="Ask!">
</form>